//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int Seat_no { get; set; }
        public int Bus_ID { get; set; }
        public string seat_status { get; set; }
        public string passenger_name { get; set; }
        public Nullable<int> booking_id { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Bus_Details Bus_Details { get; set; }
    }
}
